<?php
echo "Здарова!";
        echo "<br>";
$num = 10;
echo $num;
        echo "<br>";
$num = 33;
echo $num;
        echo "<br>";
$a = 15;
$b = $a;
echo $b;
        echo "<br>";
$num_1 = 45;
$num_2 = 63;
echo "Nomer 1 = $num_1 Nomer 2 = $num_2";
        echo "<br>";
$a=10;
$b=5;
$result = "$a+$b <br>";
echo $result;
$result = '$a+$b';
echo $result;
         echo "<br>";
$text = "Модель 'Xiaomi II'";
echo $text;
         echo "<br>";
$text = "Модель \"Xiaomi II\"";
echo $text;
         echo "<br>";
$a = null;
echo "a = $a";
         echo "<br>";
$id = 156;
echo "<p>id = $id</p>";
$id = "Region";
echo "<p>id = $id</p>";